### ISSUE TITLE
HTTL在weblogic环境下，JDK版本１.７情况下。出现编译错误。

### ISSUE THREAD

**Issue by bxvs888** [httl/httl#165]
在tomcat 下是没有问题。估计JdkCompiler编译源码的问题，请求帮助。

以下是WebLogic日志。
GET /dream-web/index.html HTTP/1.1
Connection: keep-alive
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.57 Safari/537.36
Accept-Encoding: gzip,deflate,sdch
Accept-Language: zh-CN,zh;q=0.8
Cookie: JSESSIONID=39B45565FF064203A94A7F0FC572A38D; JSESSIONID=c3w4Sp5JjC2mnkkH0h1l1JmTyTK4GcwYbSlhGJvPRPmHlGL9ZQyw!-1939543518

]] Root cause of ServletException.
java.text.ParseException: Failed to compile class, cause: Compilation failed. class: httl.spi.translators.templates.Template__index_html_GBK_1386823143373_stream, diagnostics: [Template__index_html_GBK_1386823143373_stream.java:8: 找不到符号
符号： 类 OutputStreamTemplate
位置： 软件包 httl.spi.translators.templates, Template__index_html_GBK_1386823143373_stream.java:25: 软件包 httl.spi.methods 不存在, Template__index_html_GBK_1386823143373_stream.java:26: 软件包 httl.spi.methods 不存在, Template__index_html_GBK_1386823143373_stream.java:27: 软件包 httl.spi.methods 不存在, Template__index_html_GBK_1386823143373_stream.java:28: 软件包 httl.spi.methods 不存在, Template__index_html_GBK_1386823143373_stream.java:31: 找不到符号
符号： 类 Engine
位置： 软件包 httl, Template__index_html_GBK_1386823143373_stream.java:31: 找不到符号
符号： 类 Interceptor
位置： 软件包 httl.spi, Template__index_html_GBK_1386823143373_stream.java:31: 找不到符号
符号： 类 Compiler
位置： 软件包 httl.spi, Template__index_html_GBK_1386823143373_stream.java:31: 找不到符号
符号： 类 Switcher
位置： 软件包 httl.spi, Template__index_html_GBK_1386823143373_stream.java:31: 找不到符号
符号： 类 Switcher
位置： 软件包 httl.spi, Template__index_html_GBK_1386823143373_stream.java:31: 找不到符号
符号： 类 Filter
位置： 软件包 httl.spi, Template__index_html_GBK_1386823143373_stream.java:31: 找不到符号
符号： 类 Formatter
位置： 软件包 httl.spi, Template__index_html_GBK_1386823143373_stream.java:31: 找不到符号
符号： 类 Converter
位置： 软件包 httl.spi, Template__index_html_GBK_1386823143373_stream.java:31: 找不到符号
符号： 类 Converter
位置： 软件包 httl.spi, Template__index_html_GBK_1386823143373_stream.java:31: 找不到符号
符号： 类 Resource
位置： 软件包 httl, Template__index_html_GBK_1386823143373_stream.java:31: 找不到符号
符号： 类 Template
位置： 软件包 httl, Template__index_html_GBK_1386823143373_stream.java:31: 找不到符号
符号： 类 Node
位置： 软件包 httl, Template__index_html_GBK_1386823143373_stream.java:39: 找不到符号
符号： 类 Context
位置： 软件包 httl, Template__index_html_GBK_1386823143373_stream.java:10: 软件包 httl.util 不存在, Template__index_html_GBK_1386823143373_stream.java:11: 软件包 httl.util 不存在, Template__index_html_GBK_1386823143373_stream.java:12: 软件包 httl.util 不存在, Template__index_html_GBK_1386823143373_stream.java:13: 软件包 httl.util 不存在, Template__index_html_GBK_1386823143373_stream.java:14: 软件包 httl.util 不存在, Template__index_html_GBK_1386823143373_stream.java:15: 软件包 httl.util 不存在, Template__index_html_GBK_1386823143373_stream.java:16: 软件包 httl.util 不存在, Template__index_html_GBK_1386823143373_stream.java:17: 软件包 httl.util 不存在, Template__index_html_GBK_1386823143373_stream.java:18: 软件包 httl.util 不存在, Template__index_html_GBK_1386823143373_stream.java:19: 软件包 httl.util 不存在, Template__index_html_GBK_1386823143373_stream.java:20: 软件包 httl.util 不存在, Template__index_html_GBK_1386823143373_stream.java:21: 软件包 httl.util 不存在, Template__index_html_GBK_1386823143373_stream.java:22: 软件包 httl.util 不存在, Template__index_html_GBK_1386823143373_stream.java:23: 软件包 httl.util 不存在, Template__index_html_GBK_1386823143373_stream.java:33: 软件包 httl.spi.methods 不存在, Template__index_html_GBK_1386823143373_stream.java:33: 软件包 httl.spi.methods 不存在, Template__index_html_GBK_1386823143373_stream.java:34: 软件包 httl.spi.methods 不存在, Template__index_html_GBK_1386823143373_stream.java:34: 软件包 httl.spi.methods 不存在, Template__index_html_GBK_1386823143373_stream.java:35: 软件包 httl.spi.methods 不存在, Template__index_html_GBK_1386823143373_stream.java:35: 软件包 httl.spi.methods 不存在, Template__index_html_GBK_1386823143373_stream.java:36: 软件包 httl.spi.methods 不存在, Template__index_html_GBK_1386823143373_stream.java:36: 软件包 httl.spi.methods 不存在, Template__index_html_GBK_1386823143373_stream.java:40: 找不到符号
符号： 类 Filter
位置： 软件包 httl.spi, Template__index_html_GBK_1386823143373_stream.java:41: 找不到符号
符号： 类 Filter
位置： 软件包 httl.spi, Template__index_html_GBK_1386823143373_stream.java:78: 软件包 httl.util 不存在], class: httl.spi.translators.templates.Template__index_html_GBK_1386823143373_stream, stack: java.lang.IllegalStateException: Compilation failed. class: httl.spi.translators.templates.Template__index_html_GBK_1386823143373_stream, diagnostics: [Template__index_html_GBK_1386823143373_stream.java:8: 找不到符号
符号： 类 OutputStreamTemplate
位置： 软件包 httl.spi.translators.templates, Template__index_html_GBK_1386823143373_stream.java:25: 软件包 httl.spi.methods 不存在, Template__index_html_GBK_1386823143373_stream.java:26: 软件包 httl.spi.methods 不存在, Template__index_html_GBK_1386823143373_stream.java:27: 软件包 httl.spi.methods 不存在, Template__index_html_GBK_1386823143373_stream.java:28: 软件包 httl.spi.methods 不存在, Template__index_html_GBK_1386823143373_stream.java:31: 找不到符号
符号： 类 Engine
位置： 软件包 httl, Template__index_html_GBK_1386823143373_stream.java:31: 找不到符号
符号： 类 Interceptor
位置： 软件包 httl.spi, Template__index_html_GBK_1386823143373_stream.java:31: 找不到符号
符号： 类 Compiler
位置： 软件包 httl.spi, Template__index_html_GBK_1386823143373_stream.java:31: 找不到符号
符号： 类 Switcher
位置： 软件包 httl.spi, Template__index_html_GBK_1386823143373_stream.java:31: 找不到符号
符号： 类 Switcher
位置： 软件包 httl.spi, Template__index_html_GBK_1386823143373_stream.java:31: 找不到符号
符号： 类 Filter
位置： 软件包 httl.spi, Template__index_html_GBK_1386823143373_stream.java:31: 找不到符号
符号： 类 Formatter
位置： 软件包 httl.spi, Template__index_html_GBK_1386823143373_stream.java:31: 找不到符号
符号： 类 Converter
位置： 软件包 httl.spi, Template__index_html_GBK_1386823143373_stream.java:31: 找不到符号
符号： 类 Converter
位置： 软件包 httl.spi, Template__index_html_GBK_1386823143373_stream.java:31: 找不到符号
符号： 类 Resource
位置： 软件包 httl, Template__index_html_GBK_1386823143373_stream.java:31: 找不到符号
符号： 类 Template
位置： 软件包 httl, Template__index_html_GBK_1386823143373_stream.java:31: 找不到符号
符号： 类 Node
位置： 软件包 httl, Template__index_html_GBK_1386823143373_stream.java:39: 找不到符号
符号： 类 Context
位置： 软件包 httl, Template__index_html_GBK_1386823143373_stream.java:10: 软件包 httl.util 不存在, Template__index_html_GBK_1386823143373_stream.java:11: 软件包 httl.util 不存在, Template__index_html_GBK_1386823143373_stream.java:12: 软件包 httl.util 不存在, Template__index_html_GBK_1386823143373_stream.java:13: 软件包 httl.util 不存在, Template__index_html_GBK_1386823143373_stream.java:14: 软件包 httl.util 不存在, Template__index_html_GBK_1386823143373_stream.java:15: 软件包 httl.util 不存在, Template__index_html_GBK_1386823143373_stream.java:16: 软件包 httl.util 不存在, Template__index_html_GBK_1386823143373_stream.java:17: 软件包 httl.util 不存在, Template__index_html_GBK_1386823143373_stream.java:18: 软件包 httl.util 不存在, Template__index_html_GBK_1386823143373_stream.java:19: 软件包 httl.util 不存在, Template__index_html_GBK_1386823143373_stream.java:20: 软件包 httl.util 不存在, Template__index_html_GBK_1386823143373_stream.java:21: 软件包 httl.util 不存在, Template__index_html_GBK_1386823143373_stream.java:22: 软件包 httl.util 不存在, Template__index_html_GBK_1386823143373_stream.java:23: 软件包 httl.util 不存在, Template__index_html_GBK_1386823143373_stream.java:33: 软件包 httl.spi.methods 不存在, Template__index_html_GBK_1386823143373_stream.java:33: 软件包 httl.spi.methods 不存在, Template__index_html_GBK_1386823143373_stream.java:34: 软件包 httl.spi.methods 不存在, Template__index_html_GBK_1386823143373_stream.java:34: 软件包 httl.spi.methods 不存在, Template__index_html_GBK_1386823143373_stream.java:35: 软件包 httl.spi.methods 不存在, Template__index_html_GBK_1386823143373_stream.java:35: 软件包 httl.spi.methods 不存在, Template__index_html_GBK_1386823143373_stream.java:36: 软件包 httl.spi.methods 不存在, Template__index_html_GBK_1386823143373_stream.java:36: 软件包 httl.spi.methods 不存在, Template__index_html_GBK_1386823143373_stream.java:40: 找不到符号
符号： 类 Filter
位置： 软件包 httl.spi, Template__index_html_GBK_1386823143373_stream.java:41: 找不到符号
符号： 类 Filter
位置： 软件包 httl.spi, Template__index_html_GBK_1386823143373_stream.java:78: 软件包 httl.util 不存在]

java.lang.IllegalStateException: Compilation failed. class: httl.spi.translators.templates.Template__index_html_GBK_1386823143373_stream, diagnostics: [Template__index_html_GBK_1386823143373_stream.java:8: 找不到符号
符号： 类 OutputStreamTemplate
位置： 软件包 httl.spi.translators.templates, Template__index_html_GBK_1386823143373_stream.java:25: 软件包 httl.spi.methods 不存在, Template__index_html_GBK_1386823143373_stream.java:26: 软件包 httl.spi.methods 不存在, Template__index_html_GBK_1386823143373_stream.java:27: 软件包 httl.spi.methods 不存在, Template__index_html_GBK_1386823143373_stream.java:28: 软件包 httl.spi.methods 不存在, Template__index_html_GBK_1386823143373_stream.java:31: 找不到符号
符号： 类 Engine
位置： 软件包 httl, Template__index_html_GBK_1386823143373_stream.java:31: 找不到符号
符号： 类 Interceptor
位置： 软件包 httl.spi, Template__index_html_GBK_1386823143373_stream.java:31: 找不到符号
符号： 类 Compiler
位置： 软件包 httl.spi, Template__index_html_GBK_1386823143373_stream.java:31: 找不到符号
符号： 类 Switcher
位置： 软件包 httl.spi, Template__index_html_GBK_1386823143373_stream.java:31: 找不到符号
符号： 类 Switcher
位置： 软件包 httl.spi, Template__index_html_GBK_1386823143373_stream.java:31: 找不到符号
符号： 类 Filter
位置： 软件包 httl.spi, Template__index_html_GBK_1386823143373_stream.java:31: 找不到符号
符号： 类 Formatter
位置： 软件包 httl.spi, Template__index_html_GBK_1386823143373_stream.java:31: 找不到符号
符号： 类 Converter
位置： 软件包 httl.spi, Template__index_html_GBK_1386823143373_stream.java:31: 找不到符号
符号： 类 Converter
位置： 软件包 httl.spi, Template__index_html_GBK_1386823143373_stream.java:31: 找不到符号
符号： 类 Resource
位置： 软件包 httl, Template__index_html_GBK_1386823143373_stream.java:31: 找不到符号
符号： 类 Template
位置： 软件包 httl, Template__index_html_GBK_1386823143373_stream.java:31: 找不到符号
符号： 类 Node
位置： 软件包 httl, Template__index_html_GBK_1386823143373_stream.java:39: 找不到符号
符号： 类 Context
位置： 软件包 httl, Template__index_html_GBK_1386823143373_stream.java:10: 软件包 httl.util 不存在, Template__index_html_GBK_1386823143373_stream.java:11: 软件包 httl.util 不存在, Template__index_html_GBK_1386823143373_stream.java:12: 软件包 httl.util 不存在, Template__index_html_GBK_1386823143373_stream.java:13: 软件包 httl.util 不存在, Template__index_html_GBK_1386823143373_stream.java:14: 软件包 httl.util 不存在, Template__index_html_GBK_1386823143373_stream.java:15: 软件包 httl.util 不存在, Template__index_html_GBK_1386823143373_stream.java:16: 软件包 httl.util 不存在, Template__index_html_GBK_1386823143373_stream.java:17: 软件包 httl.util 不存在, Template__index_html_GBK_1386823143373_stream.java:18: 软件包 httl.util 不存在, Template__index_html_GBK_1386823143373_stream.java:19: 软件包 httl.util 不存在, Template__index_html_GBK_1386823143373_stream.java:20: 软件包 httl.util 不存在, Template__index_html_GBK_1386823143373_stream.java:21: 软件包 httl.util 不存在, Template__index_html_GBK_1386823143373_stream.java:22: 软件包 httl.util 不存在, Template__index_html_GBK_1386823143373_stream.java:23: 软件包 httl.util 不存在, Template__index_html_GBK_1386823143373_stream.java:33: 软件包 httl.spi.methods 不存在, Template__index_html_GBK_1386823143373_stream.java:33: 软件包 httl.spi.methods 不存在, Template__index_html_GBK_1386823143373_stream.java:34: 软件包 httl.spi.methods 不存在, Template__index_html_GBK_1386823143373_stream.java:34: 软件包 httl.spi.methods 不存在, Template__index_html_GBK_1386823143373_stream.java:35: 软件包 httl.spi.methods 不存在, Template__index_html_GBK_1386823143373_stream.java:35: 软件包 httl.spi.methods 不存在, Template__index_html_GBK_1386823143373_stream.java:36: 软件包 httl.spi.methods 不存在, Template__index_html_GBK_1386823143373_stream.java:36: 软件包 httl.spi.methods 不存在, Template__index_html_GBK_1386823143373_stream.java:40: 找不到符号
符号： 类 Filter
位置： 软件包 httl.spi, Template__index_html_GBK_1386823143373_stream.java:41: 找不到符号
符号： 类 Filter
位置： 软件包 httl.spi, Template__index_html_GBK_1386823143373_stream.java:78: 软件包 httl.util 不存在]
at httl.spi.compilers.JdkCompiler.doCompile(JdkCompiler.java:188)
at httl.spi.compilers.JdkCompiler.doCompile(JdkCompiler.java:161)
at httl.spi.compilers.AbstractCompiler.compile(AbstractCompiler.java:161)
at httl.spi.compilers.AdaptiveCompiler.compile(AdaptiveCompiler.java:96)
at httl.spi.translators.templates.CompiledVisitor.compile(CompiledVisitor.java:780)
at httl.spi.translators.CompiledTranslator.parseClass(CompiledTranslator.java:498)
at httl.spi.translators.CompiledTranslator.translate(CompiledTranslator.java:412)
at httl.spi.translators.MixedTranslator.translate(MixedTranslator.java:59)
at httl.spi.engines.DefaultEngine.parseTemplate(DefaultEngine.java:255)
at httl.spi.engines.DefaultEngine.getTemplate(DefaultEngine.java:233)
at httl.Engine.getTemplate(Engine.java:423)
at httl.web.springmvc.HttlView.renderMergedTemplateModel(HttlView.java:40)
at org.springframework.web.servlet.view.AbstractTemplateView.renderMergedOutputModel(AbstractTemplateView.java:167)
at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:250)
at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1060)
at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:798)
at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:716)
at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:644)
at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:549)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:227)
at weblogic.servlet.internal.StubSecurityHelper.invokeServlet(StubSecurityHelper.java:125)
at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:292)
at weblogic.servlet.internal.TailFilter.doFilter(TailFilter.java:26)
at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:42)
at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:42)
at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3496)
at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:321)
at weblogic.security.service.SecurityManager.runAs(Unknown Source)
at weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2180)
at weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2086)
at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1406)

**Comment by bxvs888** [comment]
已解决，使用 Javassist 的Compiler 就可以了。
