### ISSUE TITLE
springmvc4.1 NoSuchMethodError  httl.Engine.getTemplate(Ljava/lang/String;Ljava/util/Locale;Ljava/lang/Object;)

### ISSUE THREAD

**Issue by gomyho** [httl/httl#187]
严重: Servlet.service() for servlet [spring] in context with path [/shop-web-front] threw exception [Handler processing failed; nested exception is java.lang.NoSuchMethodError: httl.Engine.getTemplate(Ljava/lang/String;Ljava/util/Locale;Ljava/lang/Object;)Lhttl/Template;] with root cause
java.lang.NoSuchMethodError: httl.Engine.getTemplate(Ljava/lang/String;Ljava/util/Locale;Ljava/lang/Object;)Lhttl/Template;
	at com.shangpin.shop.front.conf.HttlView.renderMergedTemplateModel(HttlView.java:46)
	at org.springframework.web.servlet.view.AbstractTemplateView.renderMergedOutputModel(AbstractTemplateView.java:167)
	at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:303)

**Comment by gomyho** [comment]
使用的全注解方式，controller如下：
        @RequestMapping("/u")
	@ResponseBody
	public ModelAndView testUser(){
		Page<UserInfoDTO> users = userSrv.findByParam(“dddd");		
		ModelAndView v=ViewConstant.mv("u");
		v.addObject("userPage", users);
		return v;
	}
u.httl没有httl的指令纯html文档。
