### ISSUE TITLE
Caused by: java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by icode** [httl/httl#189]
```
Caused by: java.lang.NullPointerException: null
at httl.spi.translators.templates.Template_views__protected_top_httl_utf_8_1430248315000_stream.doRenderStream(Template_views__protected_top_httl_utf_8_1430248315000_stream.java:32) ~[classes/:1.0.11]
	at httl.spi.translators.templates.CompiledTemplate.doRender(CompiledTemplate.java:147) ~[httl-1.0.11.jar:1.0.11]
	at httl.spi.translators.templates.AbstractTemplate._render(AbstractTemplate.java:153) ~[httl-1.0.11.jar:1.0.11]
	at httl.spi.translators.templates.AbstractTemplate.access$000(AbstractTemplate.java:50) ~[httl-1.0.11.jar:1.0.11]
	at httl.spi.translators.templates.AbstractTemplate$1.render(AbstractTemplate.java:138) ~[httl-1.0.11.jar:1.0.11]
	at httl.spi.interceptors.ListenerInterceptor.render(ListenerInterceptor.java:77) ~[httl-1.0.11.jar:1.0.11]
	at httl.spi.interceptors.MultiInterceptor$1.render(MultiInterceptor.java:54) ~[httl-1.0.11.jar:1.0.11]
	at httl.spi.interceptors.MultiInterceptor.render(MultiInterceptor.java:70) ~[httl-1.0.11.jar:1.0.11]
	at httl.spi.translators.templates.AbstractTemplate.render(AbstractTemplate.java:136) ~[httl-1.0.11.jar:1.0.11]
	at httl.spi.translators.templates.AbstractTemplate.render(AbstractTemplate.java:265) ~[httl-1.0.11.jar:1.0.11]
	at httl.spi.translators.templates.AdaptiveTemplate.render(AdaptiveTemplate.java:125) ~[httl-1.0.11.jar:1.0.11]
	at httl.spi.translators.templates.Template_views_mymeeting_httl_utf_8_1430300923000_stream.doRenderStream(Template_views_mymeeting_httl_utf_8_1430300923000_stream.java:32) ~[classes/:1.0.11]
	at httl.spi.translators.templates.CompiledTemplate.doRender(CompiledTemplate.java:147) ~[httl-1.0.11.jar:1.0.11]
	at httl.spi.translators.templates.AbstractTemplate._render(AbstractTemplate.java:153) ~[httl-1.0.11.jar:1.0.11]
	at httl.spi.translators.templates.AbstractTemplate.access$000(AbstractTemplate.java:50) ~[httl-1.0.11.jar:1.0.11]
	at httl.spi.translators.templates.AbstractTemplate$1.render(AbstractTemplate.java:138) ~[httl-1.0.11.jar:1.0.11]
	at httl.spi.interceptors.ListenerInterceptor.render(ListenerInterceptor.java:77) ~[httl-1.0.11.jar:1.0.11]
	at httl.spi.interceptors.MultiInterceptor$1.render(MultiInterceptor.java:54) ~[httl-1.0.11.jar:1.0.11]
	at httl.spi.interceptors.MultiInterceptor.render(MultiInterceptor.java:70) ~[httl-1.0.11.jar:1.0.11]
	at httl.spi.translators.templates.AbstractTemplate.render(AbstractTemplate.java:136) ~[httl-1.0.11.jar:1.0.11]
	at httl.spi.translators.templates.AdaptiveTemplate.render(AdaptiveTemplate.java:141) ~[httl-1.0.11.jar:1.0.11]
	at ameba.mvc.template.internal.HttlViewProcessor.writeTemplate(HttlViewProcessor.java:170) ~[ameba-0.1.6e.jar:0.1.6e]
	at ameba.mvc.template.internal.HttlViewProcessor.writeTemplate(HttlViewProcessor.java:34) ~[ameba-0.1.6e.jar:0.1.6e]
	at ameba.mvc.template.internal.AmebaTemplateProcessor.writeTo(AmebaTemplateProcessor.java:336) ~[ameba-0.1.6e.jar:0.1.6e]
	... 34 common frames omitted
```

**Comment by icode** [comment]
配置java文件输出后出现此问题
