### ISSUE TITLE
Jfinal1.8+httl1.0.11+jdk1.7环境中，出现展现层内存溢出

### ISSUE THREAD

**Issue by 15652309089** [httl/httl#217]
在使用jfinal的时候，httl模板在jdk1.7环境下，在展现层解析的时候，会出现内存溢出的现象：

jfinal的Controller层业务已经处理完成，并打出了响应的日志信息：

``` java
JFinal action report -------- 2016-08-15 14:24:47 ------------------------------
Controller  : com.education.background.controller.SystemController.(SystemController.java:1)
Method      : toLogin
Parameter   : msg=  toUrl=/system/index  
--------------------------------------------------------------------------------
```

之后，页面开始持续等待回应服务器响应，一直到服务器后台打出：`java.lang.OutOfMemoryError: Java heap space`

httl自身收集的dump日志：

``` js
{"response":null,"request":null,"response":null,"request":null,"footer":null,"title":null,"__listener__":null,"left":null,"script":null,"css":null,"main":null,"top":null,"__listener__":null,"__listener__":null,"__listener__":}
```

**Comment by carlvine500** [comment]
切换到jdk1.6后一切正常, 上述bug的jvm dump如下：
![https://github.com/carlvine500/redisson-simple-test/blob/master/httl-bug.png](https://raw.githubusercontent.com/carlvine500/redisson-simple-test/master/httl-bug.png)

![https://github.com/carlvine500/redisson-simple-test/blob/master/httl-bug1.png](https://raw.githubusercontent.com/carlvine500/redisson-simple-test/master/httl-bug1.png)

**Comment by adamansky** [comment]
Hello! I fixed huge memory leak in JdkCompiller so you can use https://github.com/Softmotions/httl/tree/1.0.12-SNAPSHOT

* `httl.spi.compilers.JdkCompiler` was rewritten 
*  changed format of generated httl class names in  `httl.spi.translators.templates.CompiledVisitor`

These changes eliminated JdkCompiler memory leaks 
* generated httl classes can be successfully unloaded if not used
* java compiler messages are not collected forever

![httl-leak2](https://cloud.githubusercontent.com/assets/496683/22817383/9501520a-ef99-11e6-8b42-0b1457258125.png)
![httl-leak](https://cloud.githubusercontent.com/assets/496683/22817384/9501bf1a-ef99-11e6-9383-cbe5ed3bb2e7.png)

**Comment by 15652309089** [comment]
@adamansky Thank you very much!

**Comment by carlvine500** [comment]
@adamansky

I put a books.httl into src/main/resources 
and then run main , thorw java.lang.NoClassDefFoundError: httl/spi/translators/templates/Template__books_httl_main_w_ts1487763114482

```
<!--#macro(main)-->
    <table>
        <!--#for(org.Book book : books)-->
        <tr>
            <td>${book.title}</td>
        </tr>
        <!--#end-->
    </table>
<!--#end-->
```
```

public static void main(String[] args) throws Exception {
		
		ScriptEngineManager manager = new ScriptEngineManager();
		
		ScriptEngine engine = manager.getEngineByName("httl");
		 
		Bindings bindings = engine.createBindings();
		bindings.put("user", "liangfei"); // 设置执行变量
		bindings.put("welcome", "hello"); // 设置全局变量
		bindings.put("page", "test"); // 设置引擎变量
		for (int i = 0; i < Integer.MAX_VALUE; i++) {
			String result = (String) engine.eval(
					 " #set(String welcome, String page, String user)短信提醒:${welcome}, ${user}, this is ${page} page."+i); // 执行表达式
			System.out.println("==>" + result);
		}

	}
```

```
二月 22, 2017 7:43:03 下午 httl.spi.loggers.JdkLogger info
信息: Using jdk logger for httl., httl: 1.0.12-SNAPSHOT, jvm: 1.7.0_80, os: Windows 7 6.1 amd64
二月 22, 2017 7:43:03 下午 httl.spi.loggers.JdkLogger info
信息: Load httl config from /E:/Workspaces/myeclipse10/httl-test/target/classes/httl.properties in classpath., httl: 1.0.12-SNAPSHOT, jvm: 1.7.0_80, os: Windows 7 6.1 amd64
二月 22, 2017 7:43:03 下午 httl.spi.loggers.JdkLogger info
信息: Load httl template from directory E:/Workspaces/myeclipse10/httl-test/target/classes by ClasspathLoader., httl: 1.0.12-SNAPSHOT, jvm: 1.7.0_80, os: Windows 7 6.1 amd64
二月 22, 2017 7:43:04 下午 httl.spi.loggers.JdkLogger error
严重: Failed to translate template: /books.httl, cause: java.lang.reflect.InvocationTargetException: 
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at httl.spi.translators.CompiledTranslator.translate(CompiledTranslator.java:408)
	at httl.spi.translators.MixedTranslator.translate(MixedTranslator.java:59)
	at httl.spi.engines.DefaultEngine.parseTemplate(DefaultEngine.java:259)
	at httl.spi.engines.DefaultEngine.getTemplate(DefaultEngine.java:233)
	at httl.Engine.getTemplate(Engine.java:333)
	at httl.spi.engines.DefaultEngine.inited(DefaultEngine.java:403)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at httl.util.BeanFactory.createBean(BeanFactory.java:147)
	at httl.Engine.getEngine(Engine.java:127)
	at httl.Engine.getEngine(Engine.java:79)
	at httl.script.HttlScriptEngineFactory.<init>(HttlScriptEngineFactory.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.Class.newInstance(Class.java:383)
	at sun.misc.Service$LazyIterator.next(Service.java:299)
	at javax.script.ScriptEngineManager.initEngines(ScriptEngineManager.java:123)
	at javax.script.ScriptEngineManager.access$000(ScriptEngineManager.java:53)
	at javax.script.ScriptEngineManager$1.run(ScriptEngineManager.java:91)
	at javax.script.ScriptEngineManager$1.run(ScriptEngineManager.java:89)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.script.ScriptEngineManager.init(ScriptEngineManager.java:88)
	at javax.script.ScriptEngineManager.<init>(ScriptEngineManager.java:65)
	at org.Main.main(Main.java:15)
Caused by: java.lang.NoClassDefFoundError: httl/spi/translators/templates/Template__books_httl_main_w_ts1487763114482 (wrong name: httl/spi/translators/templates/Template__books_httl_w_ts1487763114482)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
	at httl.spi.compilers.JdkCompiler$TemplateClassLoader.findClass(JdkCompiler.java:250)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at httl.spi.translators.templates.Template__books_httl_w_ts1487763114482.getMacroTypes(Template__books_httl_w_ts1487763114482.java:41)
	at httl.spi.translators.templates.CompiledTemplate.initMacros(CompiledTemplate.java:168)
	at httl.spi.translators.templates.CompiledTemplate.<init>(CompiledTemplate.java:76)
	at httl.spi.translators.templates.WriterTemplate.<init>(WriterTemplate.java:49)
	at httl.spi.translators.templates.Template__books_httl_w_ts1487763114482.<init>(Template__books_httl_w_ts1487763114482.java:19)
	... 32 more
, httl: 1.0.12-SNAPSHOT, jvm: 1.7.0_80, os: Windows 7 6.1 amd64
java.text.ParseException: Failed to translate template: /books.httl, cause: java.lang.reflect.InvocationTargetException: 
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at httl.spi.translators.CompiledTranslator.translate(CompiledTranslator.java:408)
	at httl.spi.translators.MixedTranslator.translate(MixedTranslator.java:59)
	at httl.spi.engines.DefaultEngine.parseTemplate(DefaultEngine.java:259)
	at httl.spi.engines.DefaultEngine.getTemplate(DefaultEngine.java:233)
	at httl.Engine.getTemplate(Engine.java:333)
	at httl.spi.engines.DefaultEngine.inited(DefaultEngine.java:403)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at httl.util.BeanFactory.createBean(BeanFactory.java:147)
	at httl.Engine.getEngine(Engine.java:127)
	at httl.Engine.getEngine(Engine.java:79)
	at httl.script.HttlScriptEngineFactory.<init>(HttlScriptEngineFactory.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.Class.newInstance(Class.java:383)
	at sun.misc.Service$LazyIterator.next(Service.java:299)
	at javax.script.ScriptEngineManager.initEngines(ScriptEngineManager.java:123)
	at javax.script.ScriptEngineManager.access$000(ScriptEngineManager.java:53)
	at javax.script.ScriptEngineManager$1.run(ScriptEngineManager.java:91)
	at javax.script.ScriptEngineManager$1.run(ScriptEngineManager.java:89)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.script.ScriptEngineManager.init(ScriptEngineManager.java:88)
	at javax.script.ScriptEngineManager.<init>(ScriptEngineManager.java:65)
	at org.Main.main(Main.java:15)
Caused by: java.lang.NoClassDefFoundError: httl/spi/translators/templates/Template__books_httl_main_w_ts1487763114482 (wrong name: httl/spi/translators/templates/Template__books_httl_w_ts1487763114482)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
	at httl.spi.compilers.JdkCompiler$TemplateClassLoader.findClass(JdkCompiler.java:250)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at httl.spi.translators.templates.Template__books_httl_w_ts1487763114482.getMacroTypes(Template__books_httl_w_ts1487763114482.java:41)
	at httl.spi.translators.templates.CompiledTemplate.initMacros(CompiledTemplate.java:168)
	at httl.spi.translators.templates.CompiledTemplate.<init>(CompiledTemplate.java:76)
	at httl.spi.translators.templates.WriterTemplate.<init>(WriterTemplate.java:49)
	at httl.spi.translators.templates.Template__books_httl_w_ts1487763114482.<init>(Template__books_httl_w_ts1487763114482.java:19)
	... 32 more

	at httl.spi.translators.CompiledTranslator.translate(CompiledTranslator.java:428)
	at httl.spi.translators.MixedTranslator.translate(MixedTranslator.java:59)
	at httl.spi.engines.DefaultEngine.parseTemplate(DefaultEngine.java:259)
	at httl.spi.engines.DefaultEngine.getTemplate(DefaultEngine.java:233)
	at httl.Engine.getTemplate(Engine.java:333)
	at httl.spi.engines.DefaultEngine.inited(DefaultEngine.java:403)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at httl.util.BeanFactory.createBean(BeanFactory.java:147)
	at httl.Engine.getEngine(Engine.java:127)
	at httl.Engine.getEngine(Engine.java:79)
	at httl.script.HttlScriptEngineFactory.<init>(HttlScriptEngineFactory.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.Class.newInstance(Class.java:383)
	at sun.misc.Service$LazyIterator.next(Service.java:299)
	at javax.script.ScriptEngineManager.initEngines(ScriptEngineManager.java:123)
	at javax.script.ScriptEngineManager.access$000(ScriptEngineManager.java:53)
	at javax.script.ScriptEngineManager$1.run(ScriptEngineManager.java:91)
	at javax.script.ScriptEngineManager$1.run(ScriptEngineManager.java:89)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.script.ScriptEngineManager.init(ScriptEngineManager.java:88)
	at javax.script.ScriptEngineManager.<init>(ScriptEngineManager.java:65)
	at org.Main.main(Main.java:15)

二月 22, 2017 7:43:04 下午 httl.spi.loggers.JdkLogger info
信息: Preload 1 templates from directory / with suffix [.httl], httl: 1.0.12-SNAPSHOT, jvm: 1.7.0_80, os: Windows 7 6.1 amd64
==> 短信提醒:hello, liangfei, this is test page.0
......



```

**Comment by carlvine500** [comment]
I have fixed it here
carlvine500@bc6b894

**Comment by carlvine500** [comment]
fixed bug merged to :  https://github.com/Softmotions/httl
