### ISSUE TITLE
OOM when send sms with httl template

### ISSUE THREAD

**Issue by carlvine500** [httl/httl#219]
httl version: httl-script 1.0.11
jvm args: -Xmx1024m
java version: 1.7
```
public static void main(String[] args) throws Exception {
		
		ScriptEngineManager manager = new ScriptEngineManager();
		
		ScriptEngine engine = manager.getEngineByName("httl");
		
		Bindings bindings = engine.createBindings();
		bindings.put("user", "liangfei");
		bindings.put("welcome", "hello"); 
		bindings.put("page", "test"); 
		for (int i = 0; i < Integer.MAX_VALUE; i++) {
			String result = (String) engine.eval(
					 " #set(String welcome, String page, String user)短信提醒:${welcome}, ${user}, this is ${page} page."+i);
			System.out.println("==>" + result);
		}

	}
```

OOM exception:
```
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at com.sun.tools.javac.jvm.ClassReader.<init>(ClassReader.java:187)
	at com.sun.tools.javac.jvm.ClassReader.instance(ClassReader.java:226)
	at com.sun.tools.javac.main.JavaCompiler.<init>(JavaCompiler.java:331)
	at com.sun.tools.javac.main.JavaCompiler.instance(JavaCompiler.java:88)
	at com.sun.tools.javac.main.Main.compile(Main.java:424)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:132)
	at httl.spi.compilers.JdkCompiler.doCompile(JdkCompiler.java:185)
	at httl.spi.compilers.JdkCompiler.doCompile(JdkCompiler.java:161)
	at httl.spi.compilers.AbstractCompiler.compile(AbstractCompiler.java:161)
	at httl.spi.compilers.AdaptiveCompiler.compile(AdaptiveCompiler.java:96)
	at httl.spi.translators.templates.CompiledVisitor.compile(CompiledVisitor.java:780)
	at httl.spi.translators.CompiledTranslator.parseClass(CompiledTranslator.java:498)
	at httl.spi.translators.CompiledTranslator.translate(CompiledTranslator.java:407)
	at httl.spi.translators.MixedTranslator.translate(MixedTranslator.java:59)
	at httl.spi.engines.DefaultEngine.parseTemplate(DefaultEngine.java:255)
	at httl.spi.engines.DefaultEngine.getTemplate(DefaultEngine.java:233)
	at httl.Engine.getTemplate(Engine.java:378)
	at httl.spi.engines.DefaultEngine.parseTemplate(DefaultEngine.java:292)
	at httl.Engine.parseTemplate(Engine.java:448)
	at httl.script.HttlScriptEngine.compile(HttlScriptEngine.java:68)
	at httl.script.HttlScriptEngine.eval(HttlScriptEngine.java:59)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.Main.main(Main.java:24)
二月 22, 2017 6:09:41 下午 httl.spi.loggers.JdkLogger error
严重: Failed to compile class, cause: GC overhead limit exceeded, class: httl.spi.translators.templates.Template___56890b34a9b6b6d4152963f2b36fc26f_UTF_8_1487758175837_writer, code: 
================================
package httl.spi.translators.templates;

import java.util.*;
import httl.*;

public final class Template___56890b34a9b6b6d4152963f2b36fc26f_UTF_8_1487758175837_writer extends httl.spi.translators.templates.WriterTemplate {

private static final char[] $TXT1 = httl.util.CharCache.getAndRemove("917");
private static final char[] $TXT2 = httl.util.CharCache.getAndRemove("918");
private static final String $TXT3 = httl.util.StringCache.getAndRemove("1095");
private static final char[] $TXT4 = httl.util.CharCache.getAndRemove("919");
private static final String $TXT5 = httl.util.StringCache.getAndRemove("1096");
private static final char[] $TXT6 = httl.util.CharCache.getAndRemove("920");
private static final String $TXT7 = httl.util.StringCache.getAndRemove("1097");
private static final char[] $TXT8 = httl.util.CharCache.getAndRemove("921");
private static final java.util.Map $VARS = new httl.util.OrderedMap(new String[] {"welcome", "page", "user"}, new Class[] {java.lang.String.class, java.lang.String.class, java.lang.String.class});

private final httl.spi.methods.TypeMethod $httl_spi_methods_TypeMethod;
private final httl.spi.methods.CodecMethod $httl_spi_methods_CodecMethod;
private final httl.spi.methods.FileMethod $httl_spi_methods_FileMethod;
private final httl.spi.methods.MessageMethod $httl_spi_methods_MessageMethod;


public Template___56890b34a9b6b6d4152963f2b36fc26f_UTF_8_1487758175837_writer(httl.Engine engine, httl.spi.Interceptor interceptor, httl.spi.Compiler compiler, httl.spi.Switcher filterSwitcher, httl.spi.Switcher formatterSwitcher, httl.spi.Filter filter, httl.spi.Formatter formatter, httl.spi.Converter mapConverter, httl.spi.Converter outConverter, java.util.Map functions, java.util.Map importMacros, httl.Resource resource, httl.Template parent, httl.Node root) {
	super(engine, interceptor, compiler, filterSwitcher, formatterSwitcher, filter, formatter, mapConverter, outConverter, functions, importMacros, resource, parent, root);
	this.$httl_spi_methods_TypeMethod = (httl.spi.methods.TypeMethod) functions.get(httl.spi.methods.TypeMethod.class);
	this.$httl_spi_methods_CodecMethod = (httl.spi.methods.CodecMethod) functions.get(httl.spi.methods.CodecMethod.class);
	this.$httl_spi_methods_FileMethod = (httl.spi.methods.FileMethod) functions.get(httl.spi.methods.FileMethod.class);
	this.$httl_spi_methods_MessageMethod = (httl.spi.methods.MessageMethod) functions.get(httl.spi.methods.MessageMethod.class);
}

protected void doRenderWriter(httl.Context $context, java.io.Writer $output) throws java.lang.Exception {
	httl.spi.Filter $filter = getFilter($context, "filter");
	httl.spi.Filter filter = $filter;
	httl.spi.formatters.MultiFormatter $formatter = getFormatter($context, "formatter");
	httl.spi.formatters.MultiFormatter formatter = $formatter;
	java.lang.String welcome = (java.lang.String) $context.get("welcome");
	java.lang.String page = (java.lang.String) $context.get("page");
	java.lang.String user = (java.lang.String) $context.get("user");
	$output.write($TXT1);
	$output.write($TXT2);
	$output.write(doFilter(filter, $TXT3, formatter.toString($TXT3, welcome)));
	$output.write($TXT4);
	$output.write(doFilter(filter, $TXT5, formatter.toString($TXT5, user)));
	$output.write($TXT6);
	$output.write(doFilter(filter, $TXT7, formatter.toString($TXT7, page)));
	$output.write($TXT8);
}

public String getName() {
	return "/$56890b34a9b6b6d4152963f2b36fc26f";
}

public java.util.Map getVariables() {
	return $VARS;
}

protected java.util.Map getMacroTypes() {
	return new httl.util.OrderedMap(new String[0], new Class[0]);
}

public boolean isMacro() {
	return false;
}

public int getOffset() {
	return 0;
}

}
================================
, httl: 1.0.11, jvm: 1.7.0_80, os: Windows 7 6.1 amd64
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.Arrays.copyOf(Arrays.java:2367)
	at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:130)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:114)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:415)
	at java.lang.StringBuffer.append(StringBuffer.java:237)
	at java.text.MessageFormat.subformat(MessageFormat.java:1326)
	at java.text.MessageFormat.format(MessageFormat.java:860)
	at java.text.Format.format(Format.java:157)
	at java.text.MessageFormat.format(MessageFormat.java:836)
	at com.sun.tools.javac.util.JavacMessages.getLocalizedString(JavacMessages.java:200)
	at com.sun.tools.javac.util.JavacMessages.getLocalizedString(JavacMessages.java:141)
	at com.sun.tools.javac.util.AbstractDiagnosticFormatter.localize(AbstractDiagnosticFormatter.java:305)
	at com.sun.tools.javac.util.BasicDiagnosticFormatter.formatMessage(BasicDiagnosticFormatter.java:112)
	at com.sun.tools.javac.util.BasicDiagnosticFormatter.formatMeta(BasicDiagnosticFormatter.java:184)
	at com.sun.tools.javac.util.BasicDiagnosticFormatter.formatDiagnostic(BasicDiagnosticFormatter.java:100)
	at com.sun.tools.javac.util.AbstractDiagnosticFormatter.format(AbstractDiagnosticFormatter.java:114)
	at com.sun.tools.javac.util.AbstractDiagnosticFormatter.format(AbstractDiagnosticFormatter.java:66)
	at com.sun.tools.javac.util.JCDiagnostic.toString(JCDiagnostic.java:524)
	at com.sun.tools.javac.api.ClientCodeWrapper$DiagnosticSourceUnwrapper.toString(ClientCodeWrapper.java:614)
	at java.lang.String.valueOf(String.java:2849)
	at java.lang.StringBuilder.append(StringBuilder.java:128)
	at java.util.AbstractCollection.toString(AbstractCollection.java:458)
	at java.util.Collections$SynchronizedCollection.toString(Collections.java:1658)
	at java.util.Collections$UnmodifiableCollection.toString(Collections.java:1060)
	at java.lang.String.valueOf(String.java:2849)
	at java.lang.StringBuilder.append(StringBuilder.java:128)
	at httl.spi.compilers.JdkCompiler.doCompile(JdkCompiler.java:188)
	at httl.spi.compilers.JdkCompiler.doCompile(JdkCompiler.java:161)
	at httl.spi.compilers.AbstractCompiler.compile(AbstractCompiler.java:161)
	at httl.spi.compilers.AdaptiveCompiler.compile(AdaptiveCompiler.java:96)
	at httl.spi.translators.templates.CompiledVisitor.compile(CompiledVisitor.java:780)
	at httl.spi.translators.CompiledTranslator.parseClass(CompiledTranslator.java:498)


```

**Comment by carlvine500** [comment]
I have fixed it here 
https://github.com/carlvine500/httl/commit/bc6b894ddd33bfb3644c202ca19af34e18a6c25e

**Comment by carlvine500** [comment]
I have fixed it here : 
https://github.com/carlvine500/httl/commit/bc6b894ddd33bfb3644c202ca19af34e18a6c25e

**Comment by carlvine500** [comment]
fixed bug merged to :  https://github.com/Softmotions/httl
