### ISSUE TITLE
ParseException: No such class

### ISSUE THREAD

**Issue by tokazio** [httl/httl#220]
Can't figure how to resolve this:
```
java.text.ParseException: No such class Registered, cause: java.lang.IllegalStateException:
java.lang.IllegalStateException: Registered
	at httl.util.ClassUtils.forName(ClassUtils.java:168)
	at httl.spi.parsers.TemplateParser.parseGenericType(TemplateParser.java:814)
	at httl.spi.parsers.TemplateParser.scan(TemplateParser.java:350)
	at httl.spi.parsers.TemplateParser.parse(TemplateParser.java:688)
	at httl.spi.engines.DefaultEngine.parseTemplate(DefaultEngine.java:253)
	at httl.spi.engines.DefaultEngine.getTemplate(DefaultEngine.java:233)
	at httl.Engine.getTemplate(Engine.java:378)
	at httl.spi.engines.DefaultEngine.parseTemplate(DefaultEngine.java:292)
	at httl.Engine.parseTemplate(Engine.java:448)
	at net.esyo.registry.server.RegistryServerWebHandler.handle(RegistryServerWebHandler.java:36)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at sun.net.httpserver.ServerImpl$DefaultExecutor.execute(ServerImpl.java:158)
	at sun.net.httpserver.ServerImpl$Dispatcher.handle(ServerImpl.java:431)
	at sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:396)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: Registered
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at httl.util.ClassUtils._forName(ClassUtils.java:215)
	at httl.util.ClassUtils.forName(ClassUtils.java:158)
	... 19 more

Occur to offset: 341, line: 14, column: 15, char: R, in: 
/$a2ec8ea6fa67e1901a243717ed65d434
========================================
...				<!-- #for(Registered r : regs.g...
                 ^-here
========================================

```
Having a httl.properties in src/main/resources:
```
import.packages + = net.esyo.registry.server
loaders = httl.spi.loaders.FileLoader
template.directory = ./home
template.suffix =. httl
output.encoding = UTF-8
modes + = develop
modes + = debug
```

Registered is in net.esyo.registry.server

I don't understand why
`engine.getTemplate("./home/index.html");`
doesn't work and give a file not found.
`engine.parseTemplate(new String(Files.readAllBytes(Paths.get("./home/index.html"))));`
Work and give the No such class Registered

**Comment by oulaly** [comment]
the config is "template.suffix =. httl", but why template is "./home/index.html"

**Comment by JacoBlunt** [comment]
the config "template.suffix =. httl"
````                                              
                         ^ notice here is a unnecessary blank?
````
